import "./globals.css";
import { AuthUserProvider } from "./firebase/auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning >
        <div>
          <AuthUserProvider>{children}</AuthUserProvider>
        </div>
      </body>
    </html>
  );
}
