import { Inter } from 'next/font/google'
import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      {/* <h1>jo har jga chahiye</h1> */}
      {children}
      </body>

    </html>
  )
}
